coverage:
  status:
    project:
      default:
        informational: true
        target: auto
        threshold: 10%
    patch:
      default:
        informational: true
ignore:
  - "ui/src/proto/"
  - "proto/*.go"
